-- Seed locations, categories, companies and published jobs (idempotent)

insert into countries (id, code, name, currency) values
  (1, 'MZ', 'Mozambique', 'MZN'),
  (2, 'AO', 'Angola', 'AOA'),
  (3, 'ZA', 'South Africa', 'ZAR'),
  (4, 'PT', 'Portugal', 'EUR'),
  (5, 'BR', 'Brazil', 'BRL')
on conflict (id) do nothing;

insert into regions (id, country_id, name) values
  (1, 1, 'Sofala'),
  (2, 1, 'Maputo City'),
  (3, 1, 'Maputo Province'),
  (4, 1, 'Nampula'),
  (5, 1, 'Cabo Delgado'),
  (6, 1, 'Inhambane'),
  (7, 2, 'Luanda'),
  (8, 2, 'Benguela'),
  (9, 3, 'Gauteng'),
  (10, 3, 'Western Cape'),
  (11, 4, 'Lisboa'),
  (12, 4, 'Porto'),
  (13, 5, 'São Paulo'),
  (14, 5, 'Rio de Janeiro')
on conflict (id) do nothing;

insert into cities (id, region_id, name) values
  (1, 1, 'Beira'),
  (2, 1, 'Dondo'),
  (3, 2, 'Maputo'),
  (4, 3, 'Matola'),
  (5, 4, 'Nampula'),
  (6, 5, 'Pemba'),
  (7, 6, 'Maxixe'),
  (8, 7, 'Luanda'),
  (9, 8, 'Benguela'),
  (10, 9, 'Johannesburg'),
  (11, 9, 'Pretoria'),
  (12, 10, 'Cape Town'),
  (13, 11, 'Lisbon'),
  (14, 12, 'Porto'),
  (15, 13, 'São Paulo'),
  (16, 14, 'Rio de Janeiro')
on conflict (id) do nothing;

insert into categories (id, slug, name, icon) values
  (1, 'administration', 'Administration', 'clipboard'),
  (2, 'accounting-finance', 'Accounting & Finance', 'landmark'),
  (3, 'agriculture', 'Agriculture', 'sprout'),
  (4, 'banking', 'Banking', 'building'),
  (5, 'customer-service', 'Customer Service', 'headset'),
  (6, 'education', 'Education', 'graduation-cap'),
  (7, 'engineering', 'Engineering', 'wrench'),
  (8, 'healthcare', 'Healthcare', 'stethoscope'),
  (9, 'human-resources', 'Human Resources', 'users'),
  (10, 'it-technology', 'IT & Technology', 'monitor'),
  (11, 'logistics', 'Logistics', 'truck'),
  (12, 'marketing', 'Marketing', 'megaphone'),
  (13, 'sales', 'Sales', 'handshake'),
  (14, 'hospitality', 'Hospitality', 'utensils'),
  (15, 'construction', 'Construction', 'hard-hat'),
  (16, 'security', 'Security', 'shield'),
  (17, 'ngo', 'NGO', 'globe'),
  (18, 'other', 'Other', 'more-horizontal')
on conflict (id) do nothing;

insert into companies (id, owner_id, name, industry, description, website, size, country_id, region_id, city_id, approved) values
  (1, null, 'Horizon Logistics', 'Logistics', 'Regional freight and last-mile delivery across the Beira corridor.', 'https://example.com', '51-200', 1, 1, 1, true),
  (2, null, 'Atlas Finance', 'Finance', 'Corporate finance, payroll and audit for mid-market firms.', 'https://example.com', '201-500', 1, 2, 3, true),
  (3, null, 'Verde Farms', 'Agriculture', 'Commercial farming and agri-export from Sofala.', 'https://example.com', '11-50', 1, 1, 2, true),
  (4, null, 'NexaPay', 'Fintech', 'Payments infrastructure for Southern Africa.', 'https://example.com', '11-50', 1, 2, 3, true),
  (5, null, 'Coastal Hotels', 'Hospitality', 'Business and leisure hotels on the Mozambican coast.', 'https://example.com', '51-200', 1, 1, 1, true),
  (6, null, 'Lusitania Talent', 'Recruitment', 'Cross-border hiring for lusophone markets.', 'https://example.com', '11-50', 4, 11, 13, true),
  (7, null, 'Cape Digital', 'Technology', 'Product engineering studio serving African markets.', 'https://example.com', '51-200', 3, 10, 12, true),
  (8, null, 'Luanda Retail Group', 'Retail', 'National supermarket and convenience network.', 'https://example.com', '201-500', 2, 7, 8, true),
  (9, null, 'Pemba Health Collective', 'Healthcare', 'Primary care clinics and community health programmes.', 'https://example.com', '51-200', 1, 5, 6, true),
  (10, null, 'Rio Build', 'Construction', 'Commercial fit-out and civil works.', 'https://example.com', '51-200', 5, 14, 16, true)
on conflict (id) do nothing;

insert into jobs (
  id, company_id, title, category_id, country_id, region_id, city_id,
  employment_type, work_model, experience_level, salary_min, salary_max, salary_currency,
  description, responsibilities, requirements, qualifications, benefits,
  deadline, featured, urgent, status, source_name, published_at
) values
  (1, 1, 'Heavy Vehicle Driver', 11, 1, 1, 1, 'full-time', 'on-site', '1-2', 18000, 24000, 'MZN',
   'Deliver freight on the Beira corridor with a professional operations team.',
   'Plan daily routes. Inspect vehicle safety. Complete delivery notes.',
   'Valid heavy vehicle licence. Two years of professional driving.',
   'Secondary education.', 'Fuel allowance. Medical aid contribution.',
   '2026-10-15', true, false, 'published', 'recruiter', now() - interval '1 day'),
  (2, 5, 'Hotel Receptionist', 14, 1, 1, 1, 'full-time', 'on-site', 'entry', 12000, 16000, 'MZN',
   'Front desk operations for a busy coastal business hotel.',
   'Check in guests. Handle reservations. Coordinate with housekeeping.',
   'Customer service attitude. Portuguese and basic English.',
   'Hospitality certificate preferred.', 'Meals on shift. Staff room rates.',
   '2026-10-01', false, true, 'published', 'recruiter', now()),
  (3, 3, 'Farm Supervisor', 3, 1, 1, 2, 'full-time', 'on-site', '3-5', 25000, 32000, 'MZN',
   'Supervise field teams and harvest quality for commercial plots near Dondo.',
   'Lead field teams. Report yields. Maintain equipment logs.',
   'Three or more years of farm supervision.', 'Agronomy diploma.',
   'Housing allowance.', '2026-11-01', false, false, 'published', 'recruiter', now() - interval '4 days'),
  (4, 2, 'Accountant', 2, 1, 2, 3, 'full-time', 'hybrid', '3-5', 45000, 60000, 'MZN',
   'Manage month-end close and client reporting for mid-market accounts.',
   'Reconcile ledgers. Prepare management packs. Support audits.',
   'Degree in accounting. Advanced Excel.', 'OAM registration a plus.',
   'Hybrid two days in office.', '2026-10-20', true, false, 'published', 'recruiter', now() - interval '2 days'),
  (5, 4, 'Sales Representative', 13, 1, 1, 1, 'full-time', 'hybrid', '1-2', 20000, 35000, 'MZN',
   'Acquire merchants for digital payments across Sofala.',
   'Prospect merchants. Onboard new accounts. Hit monthly targets.',
   'Driving licence. Target-driven work style.', 'Any degree or equivalent experience.',
   'Uncapped commission.', '2026-10-08', false, true, 'published', 'recruiter', now() - interval '1 day'),
  (6, 4, 'Backend Engineer', 10, 1, 2, 3, 'full-time', 'remote', '3-5', 80000, 120000, 'MZN',
   'Build payment APIs used by merchants in Mozambique and South Africa.',
   'Design APIs. Own reliability. Review pull requests.',
   'Node or Python. SQL. Production experience.', 'Computer science degree or proven portfolio.',
   'Remote-first. Learning budget.', '2026-11-15', true, false, 'published', 'recruiter', now() - interval '3 days'),
  (7, 7, 'Product Designer', 10, 3, 10, 12, 'full-time', 'hybrid', '3-5', 35000, 50000, 'ZAR',
   'Design fintech and marketplace products for African markets.',
   'Run research. Ship UI systems. Partner with engineering.',
   'Figma fluency. Portfolio of shipped work.', 'Design degree optional.',
   'Hybrid Cape Town studio.', '2026-10-30', false, false, 'published', 'recruiter', now() - interval '5 days'),
  (8, 6, 'Recruitment Consultant', 9, 4, 11, 13, 'full-time', 'on-site', '1-2', 1600, 2200, 'EUR',
   'Place Portuguese-speaking talent into Iberian and PALOP roles.',
   'Source candidates. Manage clients. Report weekly pipeline.',
   'Native Portuguese. English B2.', 'HR or business studies.',
   'Commission scheme.', '2026-10-12', false, false, 'published', 'recruiter', now() - interval '6 days'),
  (9, 8, 'Store Manager', 13, 2, 7, 8, 'full-time', 'on-site', '5+', 450000, 600000, 'AOA',
   'Lead a flagship supermarket in Luanda.',
   'Own store P&L. Lead a team of 40. Maintain standards.',
   'Five years of retail management.', 'Business diploma.',
   'Performance bonus.', '2026-10-18', true, false, 'published', 'recruiter', now() - interval '2 days'),
  (10, 2, 'Finance Intern', 2, 1, 2, 3, 'internship', 'on-site', 'none', 8000, 10000, 'MZN',
   'Six-month internship supporting the audit team in Maputo.',
   'Support reconciliations. File working papers. Shadow seniors.',
   'Final-year accounting student.', 'Degree in progress.',
   'Mentorship programme.', '2026-09-30', false, false, 'published', 'recruiter', now() - interval '8 days'),
  (11, 1, 'Warehouse Supervisor', 11, 1, 1, 1, 'full-time', 'on-site', '3-5', 22000, 28000, 'MZN',
   'Run inbound and outbound operations at the Beira warehouse.',
   'Plan shifts. Keep inventory accurate. Coach operators.',
   'Warehouse systems experience.', 'Logistics certificate.',
   'Overtime pay.', '2026-10-22', false, false, 'published', 'recruiter', now() - interval '7 days'),
  (12, 4, 'Customer Success Associate', 5, 1, 2, 3, 'full-time', 'remote', 'entry', 18000, 24000, 'MZN',
   'Help merchants adopt digital payments. Fully remote in Mozambique.',
   'Onboard merchants. Resolve tickets. Escalate product issues.',
   'Clear written Portuguese.', 'Any tertiary qualification.',
   'Fully remote.', '2026-11-01', false, false, 'published', 'recruiter', now() - interval '1 day'),
  (13, 5, 'Chef de Partie', 14, 1, 1, 1, 'full-time', 'on-site', '1-2', 14000, 19000, 'MZN',
   'Join the kitchen brigade of a waterfront hotel in Beira.',
   'Prep and service. Stock control. Maintain hygiene standards.',
   'Kitchen experience.', 'Culinary school a plus.',
   'Staff meals.', '2026-10-05', false, true, 'published', 'recruiter', now()),
  (14, 6, 'Marketing Coordinator', 12, 4, 11, 13, 'contract', 'hybrid', '1-2', 1400, 1800, 'EUR',
   'Twelve-month contract supporting employer-brand campaigns in Lisbon.',
   'Content calendar. Event support. Campaign reporting.',
   'Social ads basics.', 'Marketing degree.',
   'Hybrid Lisbon office.', '2026-10-25', false, false, 'published', 'recruiter', now() - interval '9 days'),
  (15, 7, 'Data Analyst', 10, 3, 9, 10, 'full-time', 'remote', '1-2', 28000, 38000, 'ZAR',
   'Remote analytics role serving product squads from Johannesburg.',
   'Build dashboards. Analyse experiments. Present weekly insights.',
   'SQL and Python.', 'Statistics or related degree.',
   'Remote within South Africa.', '2026-11-10', true, false, 'published', 'recruiter', now() - interval '3 days'),
  (16, 9, 'Community Health Nurse', 8, 1, 5, 6, 'full-time', 'on-site', '1-2', 28000, 36000, 'MZN',
   'Primary care and outreach in Pemba and surrounding communities.',
   'Clinic consultations. Vaccination days. Health education.',
   'Nursing licence. Willingness to travel locally.', 'Nursing diploma.',
   'Housing stipend.', '2026-10-28', false, false, 'published', 'recruiter', now() - interval '2 days'),
  (17, 10, 'Site Engineer', 7, 5, 14, 16, 'full-time', 'on-site', '3-5', 8000, 12000, 'BRL',
   'Supervise commercial fit-out projects in Rio de Janeiro.',
   'Site inspections. Contractor coordination. Handover packs.',
   'Civil or construction engineering experience.', 'Engineering degree.',
   'Transport allowance.', '2026-11-05', false, false, 'published', 'recruiter', now() - interval '4 days'),
  (18, 1, 'Logistics Coordinator', 11, 1, 3, 4, 'full-time', 'on-site', 'entry', 16000, 21000, 'MZN',
   'Coordinate inbound cargo through Matola for the Beira corridor network.',
   'Schedule trucks. Track shipments. Update customers.',
   'Organised, spreadsheet-comfortable.', 'Any diploma.',
   'Transport to site.', '2026-10-19', false, false, 'published', 'recruiter', now() - interval '5 days'),
  (19, 4, 'IT Support Technician', 10, 1, 4, 5, 'full-time', 'hybrid', 'entry', 15000, 20000, 'MZN',
   'First-line support for Nampula merchants and internal staff.',
   'Ticket triage. Device setup. User training.',
   'Comfort with Windows and Android.', 'IT certificate.',
   'Phone allowance.', '2026-10-14', false, false, 'published', 'recruiter', now() - interval '6 days'),
  (20, 2, 'Payroll Officer', 2, 1, 2, 3, 'part-time', 'hybrid', '1-2', 18000, 24000, 'MZN',
   'Part-time payroll processing for Atlas Finance clients.',
   'Process monthly payroll. Answer employee queries. File statutory returns.',
   'Payroll software experience.', 'Accounting diploma.',
   'Flexible hours.', '2026-10-21', false, false, 'published', 'recruiter', now() - interval '3 days')
on conflict (id) do nothing;
