/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as CvRouteImport } from './routes/cv'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as EmployerApplicationsRouteImport } from './routes/employer.applications'
import { Route as EmployerCompanyRouteImport } from './routes/employer.company'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as VagasIndexRouteImport } from './routes/vagas.index'
import { Route as VagasCountryRouteImport } from './routes/vagas.$country'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as VagasCountryIndexRouteImport } from './routes/vagas.$country.index'
import { Route as VagasCountryRegionRouteImport } from './routes/vagas.$country.$region'
import { Route as VagasCountryRegionIndexRouteImport } from './routes/vagas.$country.$region.index'
import { Route as VagasCountryRegionCityRouteImport } from './routes/vagas.$country.$region.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCompanyRoute = EmployerCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => EmployerRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const VagasIndexRoute = VagasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VagasRoute,
} as any)
const VagasCountryRoute = VagasCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => VagasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasCountryIndexRoute = VagasCountryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VagasCountryRoute,
} as any)
const VagasCountryRegionRoute = VagasCountryRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => VagasCountryRoute,
} as any)
const VagasCountryRegionIndexRoute = VagasCountryRegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VagasCountryRegionRoute,
} as any)
const VagasCountryRegionCityRoute = VagasCountryRegionCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => VagasCountryRegionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/applications': typeof ApplicationsRoute
  '/categories': typeof CategoriesRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post-job': typeof PostJobRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/vagas': typeof VagasRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/vagas/$country': typeof VagasCountryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/vagas/': typeof VagasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/vagas/$country/$region': typeof VagasCountryRegionRouteWithChildren
  '/vagas/$country/': typeof VagasCountryIndexRoute
  '/vagas/$country/$region/$city': typeof VagasCountryRegionCityRoute
  '/vagas/$country/$region/': typeof VagasCountryRegionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/applications': typeof ApplicationsRoute
  '/categories': typeof CategoriesRoute
  '/criar-conta': typeof CriarContaRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post-job': typeof PostJobRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin': typeof AdminIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/vagas': typeof VagasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/vagas/$country': typeof VagasCountryIndexRoute
  '/vagas/$country/$region/$city': typeof VagasCountryRegionCityRoute
  '/vagas/$country/$region': typeof VagasCountryRegionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/applications': typeof ApplicationsRoute
  '/categories': typeof CategoriesRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post-job': typeof PostJobRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/vagas': typeof VagasRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/vagas/$country': typeof VagasCountryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/vagas/': typeof VagasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/vagas/$country/$region': typeof VagasCountryRegionRouteWithChildren
  '/vagas/$country/': typeof VagasCountryIndexRoute
  '/vagas/$country/$region/$city': typeof VagasCountryRegionCityRoute
  '/vagas/$country/$region/': typeof VagasCountryRegionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/applications'
    | '/categories'
    | '/companies'
    | '/criar-conta'
    | '/cv'
    | '/dashboard'
    | '/employer'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/post-job'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/vagas'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/locations'
    | '/admin/sources'
    | '/admin/users'
    | '/companies/$companyId'
    | '/employer/applications'
    | '/employer/company'
    | '/employer/jobs'
    | '/jobs/$jobId'
    | '/vagas/$country'
    | '/admin/'
    | '/companies/'
    | '/employer/'
    | '/jobs/'
    | '/vagas/'
    | '/api/auth/$'
    | '/vagas/$country/$region'
    | '/vagas/$country/'
    | '/vagas/$country/$region/$city'
    | '/vagas/$country/$region/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/applications'
    | '/categories'
    | '/criar-conta'
    | '/cv'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/post-job'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/locations'
    | '/admin/sources'
    | '/admin/users'
    | '/companies/$companyId'
    | '/employer/applications'
    | '/employer/company'
    | '/employer/jobs'
    | '/jobs/$jobId'
    | '/admin'
    | '/companies'
    | '/employer'
    | '/jobs'
    | '/vagas'
    | '/api/auth/$'
    | '/vagas/$country'
    | '/vagas/$country/$region/$city'
    | '/vagas/$country/$region'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/applications'
    | '/categories'
    | '/companies'
    | '/criar-conta'
    | '/cv'
    | '/dashboard'
    | '/employer'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/post-job'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/vagas'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/locations'
    | '/admin/sources'
    | '/admin/users'
    | '/companies/$companyId'
    | '/employer/applications'
    | '/employer/company'
    | '/employer/jobs'
    | '/jobs/$jobId'
    | '/vagas/$country'
    | '/admin/'
    | '/companies/'
    | '/employer/'
    | '/jobs/'
    | '/vagas/'
    | '/api/auth/$'
    | '/vagas/$country/$region'
    | '/vagas/$country/'
    | '/vagas/$country/$region/$city'
    | '/vagas/$country/$region/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CategoriesRoute: typeof CategoriesRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CriarContaRoute: typeof CriarContaRoute
  CvRoute: typeof CvRoute
  DashboardRoute: typeof DashboardRoute
  EmployerRoute: typeof EmployerRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PostJobRoute: typeof PostJobRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  VagasRoute: typeof VagasRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/company': {
      id: '/employer/company'
      path: '/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof EmployerCompanyRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/vagas/': {
      id: '/vagas/'
      path: '/'
      fullPath: '/vagas/'
      preLoaderRoute: typeof VagasIndexRouteImport
      parentRoute: typeof VagasRoute
    }
    '/vagas/$country': {
      id: '/vagas/$country'
      path: '/$country'
      fullPath: '/vagas/$country'
      preLoaderRoute: typeof VagasCountryRouteImport
      parentRoute: typeof VagasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$country/': {
      id: '/vagas/$country/'
      path: '/'
      fullPath: '/vagas/$country/'
      preLoaderRoute: typeof VagasCountryIndexRouteImport
      parentRoute: typeof VagasCountryRoute
    }
    '/vagas/$country/$region': {
      id: '/vagas/$country/$region'
      path: '/$region'
      fullPath: '/vagas/$country/$region'
      preLoaderRoute: typeof VagasCountryRegionRouteImport
      parentRoute: typeof VagasCountryRoute
    }
    '/vagas/$country/$region/': {
      id: '/vagas/$country/$region/'
      path: '/'
      fullPath: '/vagas/$country/$region/'
      preLoaderRoute: typeof VagasCountryRegionIndexRouteImport
      parentRoute: typeof VagasCountryRegionRoute
    }
    '/vagas/$country/$region/$city': {
      id: '/vagas/$country/$region/$city'
      path: '/$city'
      fullPath: '/vagas/$country/$region/$city'
      preLoaderRoute: typeof VagasCountryRegionCityRouteImport
      parentRoute: typeof VagasCountryRegionRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface EmployerRouteChildren {
  EmployerApplicationsRoute: typeof EmployerApplicationsRoute
  EmployerCompanyRoute: typeof EmployerCompanyRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerApplicationsRoute: EmployerApplicationsRoute,
  EmployerCompanyRoute: EmployerCompanyRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  EmployerIndexRoute: EmployerIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface VagasCountryRegionRouteChildren {
  VagasCountryRegionCityRoute: typeof VagasCountryRegionCityRoute
  VagasCountryRegionIndexRoute: typeof VagasCountryRegionIndexRoute
}

const VagasCountryRegionRouteChildren: VagasCountryRegionRouteChildren = {
  VagasCountryRegionCityRoute: VagasCountryRegionCityRoute,
  VagasCountryRegionIndexRoute: VagasCountryRegionIndexRoute,
}

const VagasCountryRegionRouteWithChildren =
  VagasCountryRegionRoute._addFileChildren(VagasCountryRegionRouteChildren)

interface VagasCountryRouteChildren {
  VagasCountryRegionRoute: typeof VagasCountryRegionRouteWithChildren
  VagasCountryIndexRoute: typeof VagasCountryIndexRoute
}

const VagasCountryRouteChildren: VagasCountryRouteChildren = {
  VagasCountryRegionRoute: VagasCountryRegionRouteWithChildren,
  VagasCountryIndexRoute: VagasCountryIndexRoute,
}

const VagasCountryRouteWithChildren = VagasCountryRoute._addFileChildren(
  VagasCountryRouteChildren,
)

interface VagasRouteChildren {
  VagasCountryRoute: typeof VagasCountryRouteWithChildren
  VagasIndexRoute: typeof VagasIndexRoute
}

const VagasRouteChildren: VagasRouteChildren = {
  VagasCountryRoute: VagasCountryRouteWithChildren,
  VagasIndexRoute: VagasIndexRoute,
}

const VagasRouteWithChildren = VagasRoute._addFileChildren(VagasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  ApplicationsRoute: ApplicationsRoute,
  CategoriesRoute: CategoriesRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  CriarContaRoute: CriarContaRoute,
  CvRoute: CvRoute,
  DashboardRoute: DashboardRoute,
  EmployerRoute: EmployerRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PostJobRoute: PostJobRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  VagasRoute: VagasRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
